/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.70
 * Generated at: 2022-01-13 04:23:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.resume;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class setting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/jstl-jstl-1.2.jar", Long.valueOf(1640751092454L));
    _jspx_dependants.put("jar:file:/C:/경력관리/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/init-resume/WEB-INF/lib/spring-webmvc-4.2.4.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1450280850000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.2.4.RELEASE.jar", Long.valueOf(1630401380897L));
    _jspx_dependants.put("jar:file:/C:/경력관리/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/init-resume/WEB-INF/lib/spring-webmvc-4.2.4.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1450280850000L));
    _jspx_dependants.put("jar:file:/C:/경력관리/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/init-resume/WEB-INF/lib/jstl-jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta id=\"_csrf\" name=\"_csrf\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.token}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("<!-- default header name is X-CSRF-TOKEN -->\n");
      out.write("<meta id=\"_csrf_header\" name=\"_csrf_header\" content=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${_csrf.headerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>코드 세팅</title>\n");
      out.write("	<link rel=\"shortcut icon\" href=\"/images/favicon.ico\">\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/jquery-ui-1.12.1.custom/jquery-ui.min.css\"/>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/jqGrid/css/ui.jqgrid.css\"/>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x\" crossorigin=\"anonymous\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" media=\"screen\" href=\"/css/main.css\" />\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"/css/detailpage.css\"/>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <script src=\"/js/jquery-3.6.0.min.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"/js/main.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"/js/setting.js\" type=\"text/javascript\"></script>\n");
      out.write("    <!-- <script src=\"/jquery-ui-1.12.1.custom/jquery-ui.min.js\" type=\"text/javascript\"></script> -->\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\" integrity=\"sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js\" integrity=\"sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"/jqGrid/js/jquery-1.7.2.min.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"/jqGrid/js/i18n/grid.locale-kr.js\" type=\"text/javascript\"></script>\n");
      out.write("    <script src=\"/jqGrid/js/jquery.jqGrid.min.js\" type=\"text/javascript\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/navbar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div>\n");
      out.write("<ul class=\"nav nav-tabs m-3\" id=\"pills-tab\" role=\"tablist\">\n");
      out.write("    <!-- 고객사 -->\n");
      out.write("    <li class=\"nav-item1\" role=\"presentation\">\n");
      out.write("        <button class=\"nav-link active\" id=\"pills-client-tab\" data-bs-toggle=\"pill\" data-bs-target=\"#pills-client\" type=\"button\" role=\"tab\" aria-controls=\"pills-client\" aria-selected=\"true\">고객사</button>\n");
      out.write("    </li>\n");
      out.write("    <!-- 교육기관 -->\n");
      out.write("    <li class=\"nav-item1\" role=\"presentation\">\n");
      out.write("        <button class=\"nav-link\" id=\"pills-institute-tab\" data-bs-toggle=\"pill\" data-bs-target=\"#pills-institute\" type=\"button\" role=\"tab\" aria-controls=\"pills-institute\" aria-selected=\"false\">교육기관</button>\n");
      out.write("    </li>\n");
      out.write("    <!-- 직위 -->\n");
      out.write("    <li class=\"nav-item1\" role=\"presentation\">\n");
      out.write("        <button class=\"nav-link\" id=\"pills-spot-tab\" data-bs-toggle=\"pill\" data-bs-target=\"#pills-spot\" type=\"button\" role=\"tab\" aria-controls=\"pills-spot\" aria-selected=\"false\">직위</button>\n");
      out.write("    </li>\n");
      out.write("    <!-- 직종 -->\n");
      out.write("    <li class=\"nav-item1\" role=\"presentation\">\n");
      out.write("        <button class=\"nav-link\" id=\"pills-occupation-tab\" data-bs-toggle=\"pill\" data-bs-target=\"#pills-occupation\" type=\"button\" role=\"tab\" aria-controls=\"pills-occupation\" aria-selected=\"false\">직종</button>\n");
      out.write("    </li> \n");
      out.write("    <!-- 직무 -->\n");
      out.write("    <li class=\"nav-item1\" role=\"presentation\">\n");
      out.write("        <button class=\"nav-link\" id=\"pills-task-tab\" data-bs-toggle=\"pill\" data-bs-target=\"#pills-task\" type=\"button\" role=\"tab\" aria-controls=\"pills-task\" aria-selected=\"false\">직무</button>\n");
      out.write("    </li>   \n");
      out.write("    <!-- 지역 -->\n");
      out.write("    <li class=\"nav-item1\" role=\"presentation\">\n");
      out.write("        <button class=\"nav-link\" id=\"pills-area-tab\" data-bs-toggle=\"pill\" data-bs-target=\"#pills-area\" type=\"button\" role=\"tab\" aria-controls=\"pills-area\" aria-selected=\"false\">지역</button>\n");
      out.write("    </li>\n");
      out.write("    <!-- 자격증 -->\n");
      out.write("    <li class=\"nav-item1\" role=\"presentation\">\n");
      out.write("        <button class=\"nav-link\" id=\"pills-qualifi-tab\" data-bs-toggle=\"pill\" data-bs-target=\"#pills-qualifi\" type=\"button\" role=\"tab\" aria-controls=\"pills-qualifi\" aria-selected=\"false\">자격증</button>\n");
      out.write("    </li>\n");
      out.write("</ul>\n");
      out.write("<div class=\"tab-content m-3\" id=\"pills-tabContent\">\n");
      out.write("    <!-- 고객사 -->\n");
      out.write("    <div class=\"tab-pane fade show active\" id=\"pills-client\" role=\"tabpanel\" aria-labelledby=\"pills-client-tab\">\n");
      out.write("        <table id=\"clientList\"></table>\n");
      out.write("        <div id=\"clientListPager\"></div>\n");
      out.write("    </div>\n");
      out.write("    <!-- 교육기관 -->\n");
      out.write("    <div class=\"tab-pane fade\" id=\"pills-institute\" role=\"tabpanel\" aria-labelledby=\"pills-institute-tab\">\n");
      out.write("        <table id=\"instituteList\"></table>\n");
      out.write("        <div id=\"instituteListPager\"></div>\n");
      out.write("    </div>\n");
      out.write("    <!-- 직위 -->\n");
      out.write("    <div class=\"tab-pane fade\" id=\"pills-spot\" role=\"tabpanel\" aria-labelledby=\"pills-spot-tab\">\n");
      out.write("        <table id=\"spotList\"></table>\n");
      out.write("        <div id=\"spotListPager\"></div>\n");
      out.write("    </div>\n");
      out.write("    <!-- 직종 -->\n");
      out.write("    <div class=\"tab-pane fade\" id=\"pills-occupation\" role=\"tabpanel\" aria-labelledby=\"pills-occupation-tab\">\n");
      out.write("        <table id=\"occupationList\"></table>\n");
      out.write("        <div id=\"occupationListPager\"></div>\n");
      out.write("    </div>\n");
      out.write("    <!-- 직무 -->\n");
      out.write("    <div class=\"tab-pane fade\" id=\"pills-task\" role=\"tabpanel\" aria-labelledby=\"pills-task-tab\">\n");
      out.write("        <table id=\"taskList\"></table>\n");
      out.write("        <div id=\"taskListPager\"></div>\n");
      out.write("    </div>\n");
      out.write("    <!-- 지역 -->\n");
      out.write("    <div class=\"tab-pane fade\" id=\"pills-area\" role=\"tabpanel\" aria-labelledby=\"pills-qualifi-tab\">\n");
      out.write("        <table id=\"areaList\"></table>\n");
      out.write("        <div id=\"areaListPager\"></div>\n");
      out.write("    </div>\n");
      out.write("    <!-- 자격증 -->\n");
      out.write("    <div class=\"tab-pane fade\" id=\"pills-qualifi\" role=\"tabpanel\" aria-labelledby=\"pills-qualifi-tab\">\n");
      out.write("        <table id=\"qualifiList\"></table>\n");
      out.write("        <div id=\"qualifiListPager\"></div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"d-flex justify-content-end\" style = \"margin-top : 30px; margin-left : 15px; font-size : 12px;\">\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary\" id=\"option-add-btn\">추가</button>\n");
      out.write("    </div>\n");
      out.write("</div>  \n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 추가 모달 -->\n");
      out.write("<div class=\"modal fade\" id=\"addSetting\" tabindex=\"-1\" aria-labelledby=\"addSettingLabel\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h5 class=\"modal-title\" id=\"addModalLabel\">추가</h5>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("            </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("                    <!-- 고객사 -->\n");
      out.write("                    <form name=\"clientForm\" method=\"post\">\n");
      out.write("                    <table border=\"0\" class=\"addTable client\">\n");
      out.write("                        <colgroup>\n");
      out.write("                            <col width=\"20%\"/>\n");
      out.write("                            <col width=\"80%\"/>\n");
      out.write("                        </colgroup>\n");
      out.write("                        <tbody>\n");
      out.write("                            <tr>\n");
      out.write("                                <td>고객사</td>\n");
      out.write("                                <td>\n");
      out.write("                                    <input type=\"text\" id=\"client_name\" name=\"name\" class=\"form-control client\" placeholder=\"고객사\">\n");
      out.write("                                </td>\n");
      out.write("                            </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                    </form>\n");
      out.write("                    <!-- 교육기관 -->\n");
      out.write("                    <form name=\"instituteForm\" method=\"post\">\n");
      out.write("                        <table border=\"0\" class=\"addTable institute\">\n");
      out.write("                            <colgroup>\n");
      out.write("                                <col width=\"20%\"/>\n");
      out.write("                                <col width=\"80%\"/>\n");
      out.write("                            </colgroup>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>교육기관명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"institute_name\" name=\"name\" class=\"form-control institute\" placeholder=\"교육기관명\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </form>\n");
      out.write("                    <!-- 직위 -->\n");
      out.write("                    <form name=\"spotForm\" method=\"post\">\n");
      out.write("                        <table border=\"0\" class=\"addTable spot\">\n");
      out.write("                            <colgroup>\n");
      out.write("                                <col width=\"20%\"/>\n");
      out.write("                                <col width=\"80%\"/>\n");
      out.write("                            </colgroup>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>직위명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"spot_name\" name=\"name\" class=\"form-control spot\" placeholder=\"직위명\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </form>\n");
      out.write("                    <!-- 직종 -->\n");
      out.write("                    <form name=\"occupationForm\" method=\"post\">\n");
      out.write("                        <table border=\"0\" class=\"addTable occupation\">\n");
      out.write("                            <colgroup>\n");
      out.write("                                <col width=\"20%\"/>\n");
      out.write("                                <col width=\"80%\"/>\n");
      out.write("                            </colgroup>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>직종명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"occupation_name\" name=\"name\" class=\"form-control occupation\" placeholder=\"직종명\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </form>\n");
      out.write("                    <!-- 직무 -->\n");
      out.write("                    <form name=\"taskForm\" method=\"post\">\n");
      out.write("                        <table border=\"0\" class=\"addTable task\">\n");
      out.write("                            <colgroup>\n");
      out.write("                                <col width=\"20%\"/>\n");
      out.write("                                <col width=\"80%\"/>\n");
      out.write("                            </colgroup>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>직무명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                    	<select name=\"occupation\" id=\"upper_task_nm\" class =\"form-select task\" >\n");
      out.write("					                        <option value=\"\">직종 선택</option>\n");
      out.write("					                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					                    </select>\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>직무명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"task_name\" name=\"name\" class=\"form-control task\" placeholder=\"직무명\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </form>\n");
      out.write("                    <!-- 지역 -->\n");
      out.write("                    <form name=\"areaForm\" method=\"post\">\n");
      out.write("                        <table border=\"0\" class=\"addTable area\">\n");
      out.write("                            <colgroup>\n");
      out.write("                                <col width=\"20%\"/>\n");
      out.write("                                <col width=\"80%\"/>\n");
      out.write("                            </colgroup>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>지역명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"arae_name\" name=\"name\" class=\"form-control area\" placeholder=\"지역명\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </form>\n");
      out.write("                    <!-- 자격증 -->\n");
      out.write("                    <form name=\"qualifiForm\" method=\"post\">\n");
      out.write("                        <table border=\"0\" class=\"addTable qualifi\">\n");
      out.write("                            <colgroup>\n");
      out.write("                                <col width=\"20%\"/>\n");
      out.write("                                <col width=\"80%\"/>\n");
      out.write("                            </colgroup>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>자격증명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"qualifi_name\" name=\"qualifi_name\" class=\"form-control qualifi\" placeholder=\"자격증명\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>발행기관</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"qualifi_issuer\" name=\"issuer\" class=\"form-control qualifi\" placeholder=\"발행기관\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary\" id=\"option-save-btn\">저장</button>\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">닫기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 수정 모달 -->\n");
      out.write("<div class=\"modal fade\" id=\"updateSetting\" tabindex=\"-1\" aria-labelledby=\"updateSettingLabel\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <h5 class=\"modal-title\" id=\"updateModalLabel\">수정</h5>\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("            </div>\n");
      out.write("                <div class=\"modal-body\">\n");
      out.write("                    <!-- 고객사 -->\n");
      out.write("                    <form name=\"clientUpdateForm\" method=\"post\">\n");
      out.write("                        <input type=\"hidden\" id=\"update_client_nm\" name=\"client_nm\">\n");
      out.write("                        <table border=\"0\" class=\"addTable client\">\n");
      out.write("                            <colgroup>\n");
      out.write("                                <col width=\"20%\"/>\n");
      out.write("                                <col width=\"80%\"/>\n");
      out.write("                            </colgroup>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>고객사</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"update_client_name\" name=\"name\" class=\"form-control client\" placeholder=\"고객사\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </form>\n");
      out.write("                    <!-- 교육기관 -->\n");
      out.write("                    <form name=\"instituteUpdateForm\" method=\"post\">\n");
      out.write("                        <input type=\"hidden\" id=\"update_institute_nm\" name=\"institute_nm\">\n");
      out.write("                        <table border=\"0\" class=\"addTable institute\">\n");
      out.write("                            <colgroup>\n");
      out.write("                                <col width=\"20%\"/>\n");
      out.write("                                <col width=\"80%\"/>\n");
      out.write("                            </colgroup>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>교육기관명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"update_institute_name\" name=\"name\" class=\"form-control institute\" placeholder=\"교육기관명\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </form>\n");
      out.write("                    <!-- 직위 -->\n");
      out.write("                    <form name=\"spotUpdateForm\" method=\"post\">\n");
      out.write("                        <input type=\"hidden\" id=\"update_spot_nm\" name=\"spot_nm\">\n");
      out.write("                        <table border=\"0\" class=\"addTable spot\">\n");
      out.write("                            <colgroup>\n");
      out.write("                                <col width=\"20%\"/>\n");
      out.write("                                <col width=\"80%\"/>\n");
      out.write("                            </colgroup>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>직위명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"update_spot_name\" name=\"name\" class=\"form-control spot\" placeholder=\"직위명\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </form>\n");
      out.write("                    <!-- 직종 -->\n");
      out.write("                    <form name=\"occupationUpdateForm\" method=\"post\">\n");
      out.write("                        <input type=\"hidden\" id=\"update_occupation_nm\" name=\"occupation_nm\">\n");
      out.write("                        <table border=\"0\" class=\"addTable occupation\">\n");
      out.write("                            <colgroup>\n");
      out.write("                                <col width=\"20%\"/>\n");
      out.write("                                <col width=\"80%\"/>\n");
      out.write("                            </colgroup>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>직종명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"update_occupation_name\" name=\"name\" class=\"form-control occupation\" placeholder=\"직종명\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </form>\n");
      out.write("                    <!-- 직무 -->\n");
      out.write("                    <form name=\"taskUpdateForm\" method=\"post\">\n");
      out.write("                        <input type=\"hidden\" id=\"update_task_nm\" name=\"task_nm\">\n");
      out.write("                        <table border=\"0\" class=\"addTable task\">\n");
      out.write("                            <colgroup>\n");
      out.write("                                <col width=\"20%\"/>\n");
      out.write("                                <col width=\"80%\"/>\n");
      out.write("                            </colgroup>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>직종명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                    	<select name=\"occupation\" id=\"update_occupation\" class =\"form-select task\" >\n");
      out.write("					                        <option value=\"\">직종 선택</option>\n");
      out.write("					                        ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					                    </select>\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>직무명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"update_task_name\" name=\"name\" class=\"form-control task\" placeholder=\"직무명\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </form>  \n");
      out.write("                    <!-- 지역 -->\n");
      out.write("                    <form name=\"areaUpdateForm\" method=\"post\">\n");
      out.write("                    <input type=\"hidden\" id=\"update_id\" name=\"id\">\n");
      out.write("                        <table border=\"0\" class=\"addTable area\">\n");
      out.write("                            <colgroup>\n");
      out.write("                                <col width=\"20%\"/>\n");
      out.write("                                <col width=\"80%\"/>\n");
      out.write("                            </colgroup>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>지역명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"update_area_name\" name=\"name\" class=\"form-control area\" placeholder=\"지역명\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </form>                  \n");
      out.write("                    <!-- 자격증 -->\n");
      out.write("                    <form name=\"qualifiUpdateForm\" method=\"post\">\n");
      out.write("                        <input type=\"hidden\" id=\"update_qualifi_nm\" name=\"qualifi_nm\">\n");
      out.write("                        <table border=\"0\" class=\"addTable qualifi\">\n");
      out.write("                            <colgroup>\n");
      out.write("                                <col width=\"20%\"/>\n");
      out.write("                                <col width=\"80%\"/>\n");
      out.write("                            </colgroup>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>자격증명</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"update_qualifi_name\" name=\"qualifi_name\" class=\"form-control qualifi\" placeholder=\"자격증명\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>발급기관</td>\n");
      out.write("                                    <td>\n");
      out.write("                                        <input type=\"text\" id=\"update_qualifi_issuer\" name=\"issuer\" class=\"form-control qualifi\" placeholder=\"발급기관\">\n");
      out.write("                                    </td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary\" id=\"option-update-btn\">수정</button>\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">닫기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/resume/setting.jsp(198,29) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("occupation");
      // /WEB-INF/views/resume/setting.jsp(198,29) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/resume/setting.jsp(198,29) '${occupation}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${occupation}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("					                        <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${occupation.occupation_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</option>\n");
            out.write("					                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/resume/setting.jsp(199,73) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${occupation.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/resume/setting.jsp(358,29) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("occupation");
      // /WEB-INF/views/resume/setting.jsp(358,29) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/resume/setting.jsp(358,29) '${occupation}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${occupation}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("					                        <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${occupation.occupation_nm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("</option>\n");
            out.write("					                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/resume/setting.jsp(359,73) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${occupation.name}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
